### ISSUE TITLE
Components are not registering when using Vue.use

### ISSUE THREAD

**Issue by denistsoi** [efellemedia/proton#1]
Given
```
import Vue from 'vue'
import Proton from '@efelle/proton'

Vue.use(Proton)
```

where a vue component template has a proton element
say `<p-button>hello</p-button>`, a console error appears where
the component is not registered.

Codesandbox link included.
https://codesandbox.io/s/4j45mpxp50

---
- Docs may need either a codesandbox to highlight components for users or, 
- perhaps updating docs to reflect update workflow.

**Comment by g0shed** [comment]
having the same problem, Vue.use not registering

**Comment by typerory** [comment]
I would like to start using Proton. Has this been resolved?

**Comment by afflexux** [comment]
Same for me. Something wrong with the entry point I think. pronton.js is not being picked up correctly from node modules. I've tried all sorts and can't work it out.

It must be something I'm doing as it appears to work for some!

**Comment by kaidesu** [comment]
So after doing some digging on this matter - it seems to be caused by the fact that I'm using Laravel Mix to compile things down. Why this is causing an issue, I'm not sure, but am looking into creating our own webpack configuration in its place to get this resolved :+1:

**Comment by afflexux** [comment]
Thank you. I look forward to using proton soon.

**Comment by kaidesu** [comment]
Fixed :v:
