### ISSUE TITLE
How Do i really get started? 

### ISSUE THREAD

**Issue by drddavi** [efellemedia/proton#14]
I have the below in main, but the styles wont take effect. 

import Proton from '@efelle/proton'

Vue.use(Proton)

**Comment by kaidesu** [comment]
Styles are not injected as part of the library. Styles are still a work in progress - trying to figure out the best approach to this.

In the meantime you can reference https://github.com/efellemedia/proton/tree/master/src/scss for your own styles.

Please note that the styles referenced are still using Tailwind v0.7.4, so adjust accordingly.
