### ISSUE TITLE
Nuxt + Proton

### ISSUE THREAD

**Issue by kalicki** [efellemedia/proton#15]
Hey,

Does this work with Nuxt with TypeScript?

I create the `plugins/proton.ts` with:
```
import Vue from 'vue'
import Proton from '@efelle/proton'

Vue.use(Proton)
```

and in `nuxt.config.ts`: `plugins: ['~/plugins/proton']`

Error:
![Screen Shot 2019-07-02 at 15 37 27](https://user-images.githubusercontent.com/3674885/60537628-54736700-9cdf-11e9-964b-8cf83df775c9.png)

**Comment by kalicki** [comment]
Fixed

Use: `plugins: [{ src: '~/plugins/proton', ssr: false }],`

**Comment by kaidesu** [comment]
Nice! Glad you got it working :+1:

**Comment by kalicki** [comment]
Any prediction for complete documentation and Tailwind 1.0 integrated into the ui?
