### ISSUE TITLE
Button: to/href needs implementation

### ISSUE THREAD

**Issue by kalicki** [efellemedia/proton#18]
```
to: {
   required: false,
   type: String | Object,
},
href: {
   required: false,
   type: String,
},
```

**Comment by kaidesu** [comment]
Open to a pull request :+1:

**Comment by cam-vanorman** [comment]
Before I take this one, @kaidesu do you know if the intention for the to/href is just for linking to a page or if it's meant to act as a `formaction`? Curious if we want to implement [HTML5 global attributes for Buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) which includes using `formaction`:

> The URL that processes the information submitted by the button. If specified, it overrides the action attribute of the button's form owner.

If we're to match the HTML5 specification for attributes on the component, should we clarify that `href`/`to` are meant to enable the button as a link?

**Comment by kaidesu** [comment]
Just linking :+1:
